<?php

/**
 * PluginKakiageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKakiageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginKakiageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginKakiage');
    }
}