all:
  stylesheets: [/opKakiagePlugin/css/main]

indexSuccess:
  stylesheets:
    - "https://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css"
  javascripts:
    - "http://code.jquery.com/jquery-latest.min.js"
    - "http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.js"
    - "http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.js"
    - "/opKakiagePlugin/js/jquery.cookie.min.js"
    - "/opKakiagePlugin/js/jquery.pjax.min.js"
    - "/opKakiagePlugin/js/kakiage.js"
