all:
  stylesheets: [/opKakiagePlugin/css/main]

indexSuccess:
  javascripts:
    - "http://code.jquery.com/jquery-latest.min.js"
    - "/opKakiagePlugin/js/jquery.cookie.min.js"
    - "/opKakiagePlugin/js/jquery.pjax.min.js"
    - "/opKakiagePlugin/js/kakiage.js"
